---
abstract: "CUDA compiler and linker wrapper for Perl's toolchain"
author:
  - 'David Mertens <dcmertens.perl.csharp@gmail.com>'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: ExtUtils-nvcc
provides:
  ExtUtils::nvcc:
    file: lib/ExtUtils/nvcc.pm
    version: 0.02
  ExtUtils::nvcc::Backend:
    file: lib/ExtUtils/nvcc/Backend.pm
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
