---
abstract: 'the library that will eventually be behind C<perl_nvcc>'
author:
  - 'David Mertens <dcmertens.perl@gmail.com>'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: ExtUtils-nvcc
provides:
  ExtUtils::nvcc:
    file: lib/ExtUtils/nvcc.pm
    version: 0.01
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
